name: CI

concurrency:
  cancel-in-progress: true
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    uses: ppizarror/workflow-actions/.github/workflows/test_python.yml@master
    strategy:
      matrix:
        python: [ 3.7, 3.8, 3.9, '3.10' ]
    with:
      os: ubuntu-latest
      python-version: ${{ matrix.python}}