name: CI

concurrency:
  cancel-in-progress: true
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    uses: ppizarror/workflow-actions/.github/workflows/test_python.yml@master
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9, '3.10' ]
    with:
      env_vars: |
        SDL_AUDIODRIVER=disk
        SDL_VIDEODRIVER=dummy
      os: ubuntu-latest
      python_version: ${{ matrix.python-version }}